apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-net
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-net
  template:
    metadata:
      labels:
        app: nginx-net
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80